name: "Test docker Build & scan"
on:
  pull_request:
    branches:
      - main

jobs:
  docker-image-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t test-image:latest src/
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'test-image:latest'
          scanners: 'vuln,secret'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '1'
