name: "Test docker Build & scan"
on:
  pull_request:
    branches:
      - main

env:
  REPO: vulnerables
  IMAGE_NAME: phpldapadmin-remote-dump

jobs:
  docker-image-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Docker build and Trivy scan
        uses: ./.github/workflows/scan.yml
        with:
          repo: ${{ env.REPO }}
          image-name: ${{ env.IMAGE_NAME }}
          tag: latest
          exit_code: 1
          severity: HIGH,CRITICAL
